### ISSUE TITLE
How to calibrate

### ISSUE THREAD

**Issue by masoudr** [FaBoPlatform/FaBo9AXIS-MPU9250-Library#2]
How can I use `configMPU9250` function to calibrate the acceleration and gyroscope?
Can you provide more information about Accel and Gyro full-scale values?
Thanks.

**Comment by ManuelRojasDev** [comment]
Hello,

configMPU9250(gyro, accel);

You cannot use this function to calibrate the gyro nor the accel.
But you can use it to determine the sensitivity scale for both the accel and the gyro.
You can use these values to set the scale range, not that the smaller the range, the higher the sensitivity.
You can do the calibration by doing some offset calculation.

Gyro:
MPU9250_GFS_250 = max 250 degrees per second
MPU9250_GFS_500 = max 500 degrees per second
MPU9250_GFS_1000 = max 1000 degrees per second
MPU9250_GFS_2000 = max 2000 degrees per second

accel:
MPU9250_AFS_2G = max 2 G's which is 9.81*2 m/s^2
MPU9250_AFS_4G = max 4 G's which is 9.81*4 m/s^2
MPU9250_AFS_8G = max 8 G's which is 9.81*8 m/s^2
MPU9250_AFS_16G = max 16 G's which is 9.81*16 m/s^2

Regards,

**Comment by masoudr** [comment]
@NODOOD Thanks, but I see topics about calibrating this sensor, I'm using this library in my project but I don't know how to calibrate the sensor. Is there any example or code for doing that yet?

**Comment by ManuelRojasDev** [comment]
Use this one 
https://github.com/NODOOD/MPU9250

this has a function that does the calibration functions in it.
